# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

In [6]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1 0 0 0 0]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [7]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]
()
[ 8 41 44]


In [8]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [9]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [10]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.82238191 0.00672259 0.22601092 0.91360775 0.5375015 ]
 [0.23976067 0.50105159 0.20706096 0.04158779 0.88339645]
 [0.18692704 0.50457132 0.84199233 0.02989144 0.97134621]
 [0.17597227 0.67482307 0.28520371 0.77754043 0.22064221]
 [0.26942082 0.32114754 0.18819022 0.90876114 0.88026087]]

[[-8.35474480e-01 -8.02541449e-01 -1.17007050e+00 -9.67741987e-01
   3.43607652e-01]
 [ 1.63373286e+00 -2.44596457e-01 -2.70286062e-01 -1.62208936e-01
   1.48192208e+00]
 [ 7.94030119e-01 -2.64227806e+00 -2.61754902e-03  1.68192209e+00
   4.81620964e-01]
 [ 7.17549809e-01  1.34847771e+00 -8.27947874e-01 -9.59090747e-02
  -1.82142937e-01]
 [ 1.43046761e+00 -6.61195389e-01 -4.97651279e-01 -1.51756731e+00
   4.52143529e-01]
 [ 2.97686619e-01  3.97603560e-02 -1.60864263e+00  9.28215624e-01
  -1.35963287e+00]
 [-1.47728035e+00 -1.94042537e+00 -3.91427884e-01  4.09518612e-01
  -6.75362649e-01]
 [-8.44984452e-01  1.75005355e+00 -2.37107671e-01 -1.39933690e+00
   3.37870930e-01]
 [-5.88426362e-01  5.1958380

In [11]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4646309097455773
0.9959092225522438


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.006722593260609977
1.7500535501436052


In [12]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 0.22277939 -0.56977308  0.17150533 -1.68390866  0.25817096  0.27576293
  0.97173606 -0.04654626  1.07564137 -1.01523797  0.04566435  1.26208256
 -1.25965691  1.20589682 -1.68517467 -0.18316205 -1.07876739 -0.41161568
 -1.2420208 ]
0.9717360620831086


In [14]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.25817096  0.27576293  0.97173606 -0.04654626  1.07564137]


In [15]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 0.22277939 -1.68390866  0.97173606 -1.01523797 -1.25965691]


In [16]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.82238191 0.00672259 0.22601092 0.91360775 0.5375015 ]
 [0.23976067 0.50105159 0.20706096 0.04158779 0.88339645]
 [0.18692704 0.50457132 0.84199233 0.02989144 0.97134621]
 [0.17597227 0.67482307 0.28520371 0.77754043 0.22064221]
 [0.26942082 0.32114754 0.18819022 0.90876114 0.88026087]]
0.20706096493789838
0.20706096493789838


In [17]:
print(rand_mat[0:2,1:3])

[[0.00672259 0.22601092]
 [0.50105159 0.20706096]]


In [18]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 0.22277939 -0.56977308  0.17150533 -1.68390866  0.25817096  0.27576293
  0.97173606 -0.04654626  1.07564137 -1.01523797  0.04566435  1.26208256
 -1.25965691  1.20589682 -1.68517467 -0.18316205 -1.07876739 -0.41161568
 -1.2420208 ]

[ 0.22277939 -0.56977308  0.17150533  4.          4.          0.27576293
  0.97173606 -0.04654626  1.07564137 -1.01523797  0.04566435  1.26208256
 -1.25965691  1.20589682 -1.68517467 -0.18316205 -1.07876739 -0.41161568
 -1.2420208 ]

[ 0.22277939 -0.56977308  0.17150533  1.          2.          0.27576293
  0.97173606 -0.04654626  1.07564137 -1.01523797  0.04566435  1.26208256
 -1.25965691  1.20589682 -1.68517467 -0.18316205 -1.07876739 -0.41161568
 -1.2420208 ]


In [20]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[3.         3.         3.         0.91360775 0.5375015 ]
 [3.         3.         3.         0.04158779 0.88339645]
 [0.18692704 0.50457132 0.84199233 0.02989144 0.97134621]
 [0.17597227 0.67482307 0.28520371 0.77754043 0.22064221]
 [0.26942082 0.32114754 0.18819022 0.90876114 0.88026087]]

[[3.         3.         3.         0.91360775 0.5375015 ]
 [3.         3.         3.         0.         0.        ]
 [0.18692704 0.50457132 0.84199233 0.         0.        ]
 [0.17597227 0.67482307 0.28520371 0.77754043 0.22064221]
 [0.26942082 0.32114754 0.18819022 0.90876114 0.88026087]]


In [19]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.82238191 0.00672259 0.22601092]
 [0.23976067 0.50105159 0.20706096]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [ ]:
print(rand_mat)

In [21]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.91360775 0.5375015 ]
 [3.         3.         3.         0.         0.        ]
 [0.18692704 0.50457132 0.84199233 0.         0.        ]
 [0.17597227 0.67482307 0.28520371 0.77754043 0.22064221]
 [0.26942082 0.32114754 0.18819022 0.90876114 0.88026087]]


In [22]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.02811921 -1.29977871  1.12352788 -0.0359103  -1.47282008 -1.03647963
 -0.22494683 -0.72638037 -0.1232407   1.55035393  0.74859239 -0.67989804
  0.37791966  1.10435047  0.54961742]
[False False  True False False False False False False  True  True False
  True  True  True]
[1.12352788 1.55035393 0.74859239 0.37791966 1.10435047 0.54961742]


In [23]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-8.35474480e-01 -8.02541449e-01 -1.17007050e+00 -9.67741987e-01
   3.43607652e-01]
 [ 1.63373286e+00 -2.44596457e-01 -2.70286062e-01 -1.62208936e-01
   1.48192208e+00]
 [ 7.94030119e-01 -2.64227806e+00 -2.61754902e-03  1.68192209e+00
   4.81620964e-01]
 [ 7.17549809e-01  1.34847771e+00 -8.27947874e-01 -9.59090747e-02
  -1.82142937e-01]
 [ 1.43046761e+00 -6.61195389e-01 -4.97651279e-01 -1.51756731e+00
   4.52143529e-01]
 [ 2.97686619e-01  3.97603560e-02 -1.60864263e+00  9.28215624e-01
  -1.35963287e+00]
 [-1.47728035e+00 -1.94042537e+00 -3.91427884e-01  4.09518612e-01
  -6.75362649e-01]
 [-8.44984452e-01  1.75005355e+00 -2.37107671e-01 -1.39933690e+00
   3.37870930e-01]
 [-5.88426362e-01  5.19583805e-01  7.46842893e-02 -1.15838233e+00
   3.45183973e-01]
 [ 2.51400354e-01 -1.07950709e+00 -6.23134241e-01 -1.49764555e+00
   9.61995320e-02]]
[0.34360765 1.63373286 1.48192208 0.79403012 1.68192209 0.48162096
 0.71754981 1.34847771 1.43046761 0.45214353 0.29768662 0.03976036
 0.92821562 0.4

In [24]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.02811921 -1.29977871  1.12352788 -0.0359103  -1.47282008 -1.03647963
 -0.22494683 -0.72638037 -0.1232407   1.55035393  0.74859239 -0.67989804
  0.37791966  1.10435047  0.54961742]

[-0.02811921 -1.29977871 -5.         -0.0359103  -1.47282008 -1.03647963
 -0.22494683 -0.72638037 -0.1232407  -5.         -5.         -0.67989804
  0.37791966 -5.         -5.        ]


In [25]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [26]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [27]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-8.35474480e-01 -8.02541449e-01 -1.17007050e+00 -9.67741987e-01
   3.43607652e-01]
 [ 1.63373286e+00 -2.44596457e-01 -2.70286062e-01 -1.62208936e-01
   1.48192208e+00]
 [ 7.94030119e-01 -2.64227806e+00 -2.61754902e-03  1.68192209e+00
   4.81620964e-01]
 [ 7.17549809e-01  1.34847771e+00 -8.27947874e-01 -9.59090747e-02
  -1.82142937e-01]
 [ 1.43046761e+00 -6.61195389e-01 -4.97651279e-01 -1.51756731e+00
   4.52143529e-01]
 [ 2.97686619e-01  3.97603560e-02 -1.60864263e+00  9.28215624e-01
  -1.35963287e+00]
 [-1.47728035e+00 -1.94042537e+00 -3.91427884e-01  4.09518612e-01
  -6.75362649e-01]
 [-8.44984452e-01  1.75005355e+00 -2.37107671e-01 -1.39933690e+00
   3.37870930e-01]
 [-5.88426362e-01  5.19583805e-01  7.46842893e-02 -1.15838233e+00
   3.45183973e-01]
 [ 2.51400354e-01 -1.07950709e+00 -6.23134241e-01 -1.49764555e+00
   9.61995320e-02]]



In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)